# Generated by Django 2.2.7 on 2019-11-15 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(default='owner account deleted. ', on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
