# Generated by Django 2.2.7 on 2019-11-15 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sunchaser', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='owner',
        ),
        migrations.AddField(
            model_name='journey',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='journeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
